### ISSUE TITLE
Exception Handlers

### ISSUE THREAD

**Issue by clbertolini** [ezasm-org/EzASM#130]
**As a** User
**I want** The ability to handle exceptions (Overflow, Memory Access, etc.) as well as definitions for the different exceptions that can occur.
**So that** I can detect and handle exceptions and other unexpected behavior.

**Request Description**
I either want some way to assign assembly procedures that can be run when an exception occurs or some standardized behavior that will occur when execution of EzASM code triggers an exception.

**Additional context**
At the very least there should be well-defined behavior in the wiki for exceptions and some way for the program to exit gracefully.

**Comment by TrevorBrunette** [comment]
This will be addressed via documentation on instructions for many cases. Errors reached by a read or write out of bounds and such would be equivalent to a segmentation fault. Since some errors cannot be recovered from, this makes sense. Perhaps certain recoverable errors should set an error register if they error rather than exiting, such as `readi` attempting to parse something that is not an integer. Does anyone else have input on this?
